networks:
  piima_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piima_app
    env_file: .env  # Load environment variables from the .env file
    ports:
      - "3132:3132"  # Map port 3131 to the host
    networks:
      - piima_network
    restart: always  # Restart the container if it stops
    depends_on:
      - postgres  # Ensure Postgres starts first

  postgres:
    image: postgres:13
    container_name: piima_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Use password from .env
      POSTGRES_DB: ${POSTGRES_DB}              # Use database name from .env
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}"  # Map PostgreSQL's default port to the specified port
    networks:
      - piima_network
    restart: always  # Restart the container if it stops
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data between restarts

volumes:
  postgres_data:
